name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev vulkan-tools libglfw3-dev libglm-dev build-essential

    - name: Configure CMake
      # This creates the 'build' directory and generates the Makefile
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build with Make
      # This enters the build directory and runs 'make'
      run: make -C build
